### ISSUE TITLE
I2C Manager and more  (Thank you for inspiring me...)

### ISSUE THREAD

**Issue by ropg** [tuupola/esp_i2c_hal#3]
Hello Mika. Pleased to meet you...

I think you might like I2C Manager. It does the same thing as I2C Helper, but offers quite a few more features. At the same time, it still lets people use all the platform-agnostic code you wrote (thank you for that), even making your code easier to use. 

Here's [I2C Manager itself](https://github.com/ropg/i2c_manager), and here is a [sample project for M5Core2](https://github.com/ropg/m5core2_esp-idf_demo), showing some other components I did and so you can see it all in action.

Regards,

Rop

**Comment by tuupola** [comment]
Looks great! I can link it from some of my I2C drivers as suggestion for a thread safe I2C helper. For inspiration there is also [i2cdev](https://github.com/UncleRus/esp-idf-lib/tree/master/components/i2cdev) by @UncleRus. Might be worth checking out. The project also has drivers for huge amounts of different chips.

**Comment by ropg** [comment]
Oh wow, thanks for the link, I was not aware. 

I'll make sure my implementation plays nice with his, coupling the mutexes somehow. @UncleRus is a bit sparse on README, but I'll check it out when I have time.

Please also have a look at my PR for axp192. I'd love to remove dependencies on my modified version. (If you like the mods, that is.)
